import * as mongo from 'mongo';
const SearchedQuestionSchema = new mongo.Schema({
  _id: String, // unique id generated by Mongo
  title: String,
  author: String,
  timestamp: Number,
  query: String,
  scripture: [{verseId: String}],
});
export const SearchedQuestion = mongo.model('SearchedQuestion', SearchedQuestionSchema);